using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace SouthernTravelsWeb.DAL.DbObjects
{
    public static class StoredProcedures
    {
        public const string Fixed_DatewiseTours_Vacantseats = "Fixed_DatewiseTours_Vacantseats";
        public const string GetNewsNotificationList_sp = "GetNewsNotificationList_sp";
        public const string Get_EnqueryCode = "Get_EnqueryCode";
        public const string sp_GetTourStartFrom = "sp_GetTourStartFrom";
        public const string sp_GetToursByTypeAndStartFrom = "sp_GetToursByTypeAndStartFrom";
        public const string GetTourS_Search_SP = "GetTourS_Search_SP";
        public const string GetSpecialTourJourneyDate_SP = "GetSpecialTourJourneyDate_SP";
        public const string GetLastJourneyDateAll_SP = "GetLastJourneyDateAll_SP";
        public const string TourItenerary_SP = "TourItenerary_SP";
        public const string GetTourList_By_Start_Region = "GetTourList_By_Start_Region";
        public const string GetTourListSearchWithPagging_SP = "GetTourListSearchWithPagging_SP";
        public const string GetTourItinerary_Meal_sp = "GetTourItinerary_Meal_sp";
        public const string sp_GetCityDetail = "sp_GetCityDetail";
        public const string GetMetTagForTours_sp = "GetMetTagForTours_sp";
        public const string sp_tbl_intquery = "sp_tbl_intquery";
        public const string GetTourListSearch_SP = "GetTourListSearch_SP";
        public const string GetTourZone_SP = "GetTourZone_SP";
        public const string GetSimilarPKGEndUser_SP = "GetSimilarPKGEndUser_SP";
        public const string insert_SmsSend_tbl = "insert_SmsSend_tbl";
        public const string GetIntMenu_sp = "GetIntMenu_sp";
        public const string GetTourInfo_SP = "GetTourInfo_SP";
        public const string GetTourItinerary_Meal = "GetTourItinerary_Meal";
        public const string GetTourPlaceInfo_SP = "GetTourPlaceInfo_SP";
        public const string GetTourStartFromSearch_SP = "GetTourStartFromSearch_SP";
        public const string SaveCustomerContactUS_SP = "SaveCustomerContactUS_SP";
        public const string SaveCustomerFeedback_SP = "SaveCustomerFeedback_SP";
        public const string FeedBackHierarchy_sp = "FeedBackHierarchy_sp";
        public const string ins_Enq_tbl = "ins_Enq_tbl";
        public const string sp_GetState = "sp_GetState";
        public const string SaveVendor_Hotel_SP = "SaveVendor_Hotel_SP";
        public const string FindTourDetail_sp = "FindTourDetail_sp";
        public const string Get_Fare_Panel_IsQuery_sp = "Get_Fare_Panel_IsQuery_sp";
        public const string GetFixedTourJourneyDate_SP = "GetFixedTourJourneyDate_SP";
        public const string jdates_vacantseats= "jdates_vacantseats";
        public const string SP_Update_EBK_TCSVAL = "SP_Update_EBK_TCSVAL";
         public const string LogError_sp = "LogError_sp";
        public const string GST_GetCityListByStateIdAndSearchedCityText = "GST_GetCityListByStateIdAndSearchedCityText";
        public const string GST_FindTourDetail_sp = "GST_FindTourDetail_sp";
        public const string GetCountryWiseStateName_SP = "GetCountryWiseStateName_SP";
        public const string SaveAgentLogInInfo_sp = "SaveAgentLogInInfo_sp";
        public const string customer_login = "customer_login";
        public const string customer_updatepassword = "customer_updatepassword";
        public const string Agent_ForgotPassword = "Agent_ForgotPassword";
         public const string agent_session_details = "agent_session_details";
        public const string ValidateAgent_sp = "ValidateAgent_sp";
        public const string insert_OnlineCustomer = "insert_OnlineCustomer";
        public const string Check_UpdateCustomerEmailMobile = "Check_UpdateCustomerEmailMobile";
        public const string onlinecustomer_details = "onlinecustomer_details";
        public const string update_OnlineCustomer_PWD = "update_OnlineCustomer_PWD";
        public const string update_OnlineCustomer = "update_OnlineCustomer";
        public const string customer_bookedtickets = "customer_bookedtickets";
        public const string customer_journeydate = "customer_journeydate";
        public const string request_ltc = "request_ltc";
        public const string customer_cancelledtickets = "customer_cancelledtickets";
        public const string CheckInMbkTicket_sp = "CheckInMbkTicket_sp";
        public const string GetExtraServiceCollectionDetails_sp = "GetExtraServiceCollectionDetails_sp";
        public const string UpdateTicketDeatilsByOrderID = "UpdateTicketDeatilsByOrderID";
        public const string MBKGetGroupEnquiryByOrderID_sp = "MBKGetGroupEnquiryByOrderID_sp";
        public const string InsertPaymentDetail_Sp = "InsertPaymentDetail_Sp";
        public const string OnlineBalanceClear_sp = "OnlineBalanceClear_sp";
        public const string InsertPaymentHDFCPG_SP = "InsertPaymentHDFCPG_SP";
        public const string customer_splbookedtickets = "customer_splbookedtickets";
        public const string customer_Groupbookedtickets = "customer_Groupbookedtickets";
        public const string GetTourStratFrom_SP = "GetTourStratFrom_SP";
        public const string FindSpl_TourMaster_sp = "FindSpl_TourMaster_sp";
        public const string Get_SpecialTour_FarePanel_NEW_sp = "Get_SpecialTour_FarePanel_NEW_sp";
        public const string GetTour_sp = "GetTour_sp";
        public const string GetServiceTaxIsAcc_sp = "GetServiceTaxIsAcc_sp";
        public const string GetServiceTaxValue_sp = "GetServiceTaxValue_sp";
        public const string GetCombinationTour_sp = "GetCombinationTour_sp";
        public const string GetLTCCharges_sp = "GetLTCCharges_sp";
        public const string RowWiseTourID_sp = "RowWiseTourID_sp";
        public const string DeleteOnlineToursBooking_sp = "DeleteOnlineToursBooking_sp";
        public const string GetCustomerDetail_sp = "GetCustomerDetail_sp";
        public const string SaveTransactionByPromoCode_sp = "SaveTransactionByPromoCode_sp";
        public const string GetSumOfTourAmt_sp = "GetSumOfTourAmt_sp";
        public const string insert_tbl_PaymentDetails = "insert_tbl_PaymentDetails";
        public const string GetPickUpMAsterRowID_sp = "GetPickUpMAsterRowID_sp";
        public const string GetDiscount_Detail = "GetDiscount_Detail";
        public const string GetFbDetail_sp = "GetFbDetail_sp";
        public const string GetCountryName_SP = "GetCountryName_SP";
        public const string GetCustRowID_sp = "GetCustRowID_sp";
        public const string GST_InsertUpdateCustDetail_sp = "GST_InsertUpdateCustDetail_sp";
        public const string sp_NoOfSeats = "sp_NoOfSeats";
        public const string sp_GetTAXValue = "sp_GetTAXValue";
        public const string sp_GetSeatArrangement = "sp_GetSeatArrangement";
        public const string Get_FixedTour_Fare = "Get_FixedTour_Fare";
        public const string SP_AddOperatingBranchForEBK_SPL = "SP_AddOperatingBranchForEBK_SPL";
        public const string Fixed_PickupAddr_DeptTime = "Fixed_PickupAddr_DeptTime";
        public const string Fixed_Default_PickupAddress = "Fixed_Default_PickupAddress";
        public const string dispup_sp = "dispup_sp";
        public const string GetMultiplePickupPoint_sp = "GetMultiplePickupPoint_sp";
        public const string Get_VacantSeats = "Get_VacantSeats";
        public const string BlockUnBlockSeats_sp= "BlockUnBlockSeats_sp";
        public const string GetBusAllot_Detail_sp = "GetBusAllot_Detail_sp";
        public const string GetOrderID_sp = "GetOrderID_sp";
        public const string ValidateDiscount_sp = "ValidateDiscount_sp";
        public const string ChkBusType_sp = "ChkBusType_sp";
        public const string Fixed_TourSerial = "Fixed_TourSerial";
        public const string TourWiseTourSr_sp = "TourWiseTourSr_sp";
        public const string SeatDetail_sp = "SeatDetail_sp";
        public const string UpdaterTourDeatil_sp = "UpdaterTourDeatil_sp";
        public const string GetJourneyDate_sp = "GetJourneyDate_sp";
        public const string GST_ExistCustomerDetail_sp = "GST_ExistCustomerDetail_sp";
        public const string Check_Promocode = "Check_Promocode";
        public const string GetToursBookingInfo_sp = "GetToursBookingInfo_sp";
        public const string insertbook_sp = "insertbook_sp";
        public const string Updatebook_sp = "Updatebook_sp";

    }


}