name: SonarQube Analysis

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '6.0.x'  # or 7.0/8.0 depending on your project

      - name: Install MSBuild
        uses: microsoft/setup-msbuild@v2

      - name: SonarQube Begin
        run: |
          .\.sonar\scanner\dotnet-sonarscanner begin /k:"Durgesh1808_SouthernTravelsWeb" /o:"durgesh1808" /d:sonar.token="${{ secrets.SONAR_TOKEN }}" /d:sonar.host.url="https://sonarcloud.io"

      - name: Build Solution
        run: msbuild SouthernTravelsWeb.sln /t:Rebuild

      - name: SonarQube End
        run: |
          .\.sonar\scanner\dotnet-sonarscanner end /d:sonar.token="${{ secrets.SONAR_TOKEN }}"
